import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
import streamlit as st
import pandas as pd
import datetime
import os
import numpy as np
import time
import random 
from PIL import Image
from fpdf import FPDF
from database_utils import get_connection
from streamlit_drawable_canvas import st_canvas

conn = get_connection()

# --- DB PATCH: Add document_url to users table ---
try: 
    conn.execute("ALTER TABLE users ADD COLUMN document_url TEXT")
    conn.commit()
except Exception: 
    pass
# -------------------------------------------------

# Creates uploads folder for asset photos
if not os.path.exists("uploads"): 
    os.makedirs("uploads")

# Utility to save uploaded images locally
def save_file(uploaded_file):
    if uploaded_file:
        path = os.path.join("uploads", uploaded_file.name)
        with open(path, "wb") as f: 
            f.write(uploaded_file.getbuffer())
        return path
    return None

# --- PDF GENERATION ENGINE WITH LOGO INTEGRATION ---
def generate_contract(booking_ref, renter, vehicle, plate, chk_data, sig_r, sig_a, is_with_driver=False, driver_name=""):
    pdf = FPDF()
    pdf.add_page()
    try:
        pdf.image("logo.png", x=80, y=10, w=50)
        pdf.set_y(45) 
    except Exception: 
        pdf.set_y(20)
    pdf.set_font("Helvetica", 'B', 16)
    pdf.cell(0, 10, "DRIVEELITE HANDOVER AGREEMENT (LUZON USE ONLY)", ln=True, align='C')
    pdf.set_font("Helvetica", '', 12)
    pdf.cell(0, 10, f"Ref: {booking_ref} | Date: {datetime.date.today()}", ln=True)
    pdf.cell(0, 10, f"Vehicle: {vehicle} ({plate}) | Renter: {renter}", ln=True)
    if is_with_driver and driver_name: 
        pdf.cell(0, 10, f"Assigned Driver: {driver_name}", ln=True)
    pdf.ln(10)
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(0, 10, "VERIFIED HANDOVER CHECKLIST:", ln=True)
    pdf.set_font("Helvetica", '', 11)
    for item in chk_data: 
        pdf.cell(0, 8, f"[ OK ]  {item}", ln=True)
    current_y = pdf.get_y() + 10
    try:
        if sig_r is not None:
            Image.fromarray(sig_r.astype('uint8'), 'RGBA').convert('RGB').save("tr.jpg", "JPEG")
            pdf.image("tr.jpg", x=20, y=current_y, w=50)
        if sig_a is not None:
            Image.fromarray(sig_a.astype('uint8'), 'RGBA').convert('RGB').save("ta.jpg", "JPEG")
            pdf.image("ta.jpg", x=120, y=current_y, w=50)
    except Exception: 
        pass
    sig_label = "Driver Signature" if is_with_driver else "Affiliate Signature"
    pdf.set_xy(20, current_y + 40)
    pdf.cell(50, 5, "Renter Signature", align='C')
    pdf.set_xy(120, current_y + 40)
    pdf.cell(50, 5, sig_label, align='C')
    pdf.ln(20)
    pdf.set_font("Helvetica", 'I', 9)
    pdf.cell(0, 5, "Legally generated by DriveElite Platform", align='C')
    return pdf.output(dest="S").encode("latin-1")

def generate_return_receipt(booking_ref, renter, vehicle, plate, fuel, clean, damage, late, ot_fee, rfid_fee, total_deduct, refund, sig_ret, sig_reta, is_with_driver=False, driver_name=""):
    pdf = FPDF()
    pdf.add_page()
    try:
        pdf.image("logo.png", x=80, y=10, w=50)
        pdf.set_y(45) 
    except Exception: 
        pdf.set_y(20)
    pdf.set_font("Helvetica", 'B', 16)
    pdf.cell(0, 10, "DRIVEELITE RETURN & SETTLEMENT RECEIPT", ln=True, align='C')
    pdf.set_font("Helvetica", '', 12)
    pdf.cell(0, 10, f"Ref: {booking_ref} | Date: {datetime.date.today()}", ln=True)
    pdf.cell(0, 10, f"Vehicle: {vehicle} ({plate}) | Renter: {renter}", ln=True)
    pdf.ln(10)
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(0, 10, "SECURITY DEPOSIT DEDUCTIONS:", ln=True)
    pdf.set_font("Helvetica", '', 11)
    pdf.cell(0, 8, f"Fuel Replacement: Php {fuel:,.2f}", ln=True)
    pdf.cell(0, 8, f"Cleaning Penalty: Php {clean:,.2f}", ln=True)
    pdf.cell(0, 8, f"Damage Penalty: Php {damage:,.2f}", ln=True)
    pdf.cell(0, 8, f"RFID Load Used: Php {rfid_fee:,.2f}", ln=True)
    pdf.cell(0, 8, f"Late Penalty: Php {late:,.2f}", ln=True)
    pdf.ln(5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_font("Helvetica", '', 12)
    pdf.cell(0, 8, f"Total Deductions: Php {total_deduct:,.2f}", ln=True)
    pdf.cell(0, 8, f"Less Initial Deposit: (Php 5,000.00)", ln=True)
    pdf.ln(2) 
    pdf.set_font("Helvetica", 'B', 12)
    if total_deduct > 5000.0:
        amount_payable = total_deduct - 5000.0
        pdf.cell(0, 10, f"NET PAYABLE TO AFFILIATE: Php {amount_payable:,.2f}", ln=True)
    else:
        pdf.cell(0, 10, f"NET REFUND TO RENTER: Php {refund:,.2f}", ln=True)
    current_y = pdf.get_y() + 15
    try:
        if sig_ret is not None:
            Image.fromarray(sig_ret.astype('uint8'), 'RGBA').convert('RGB').save("tret.jpg", "JPEG")
            pdf.image("tret.jpg", x=20, y=current_y, w=50)
        if sig_reta is not None:
            Image.fromarray(sig_reta.astype('uint8'), 'RGBA').convert('RGB').save("treta.jpg", "JPEG")
            pdf.image("treta.jpg", x=120, y=current_y, w=50)
    except Exception: 
        pass
    pdf.set_xy(20, current_y + 40)
    pdf.cell(50, 5, "Renter Final Sign-off", align='C')
    pdf.set_xy(120, current_y + 40)
    pdf.cell(50, 5, "Affiliate Final Sign-off", align='C')
    pdf.ln(20)
    pdf.set_font("Helvetica", 'I', 9)
    pdf.cell(0, 5, "Legally generated by DriveElite Platform", align='C')
    return pdf.output(dest="S").encode("latin-1")

def send_pdf_email(to_email, subject, body, pdf_bytes, filename):
    sender_email = "rdalbaojrh@gmail.com" 
    app_password = "f22c3FF18pr" 
    if not to_email or "@" not in to_email:
        return False, "No valid email address provided."
    msg = MIMEMultipart()
    msg['From'] = f"DriveElite Admin <{sender_email}>"
    msg['To'] = to_email
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain'))
    part = MIMEBase('application', 'octet-stream')
    part.set_payload(pdf_bytes)
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', f"attachment; filename= {filename}")
    msg.attach(part)
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, app_password)
        server.send_message(msg)
        server.quit()
        return True, "Email sent successfully!"
    except Exception as e:
        return False, str(e)

st.set_page_config(page_title="DriveElite Affiliate Portal", layout="wide")
conn = get_connection()

try:
    cat_df = pd.read_sql_query("SELECT name, default_price FROM vehicle_categories", conn)
    FIXED_RATES = dict(zip(cat_df['name'], cat_df['default_price']))
except Exception: 
    FIXED_RATES = {"Sedan": 1500.0} 

if not st.session_state.get('logged_in') or st.session_state.get('role') != 'AFFILIATE':
    logo_col1, logo_col2, logo_col3 = st.columns([1, 2, 1])
    with logo_col2:
        try: 
            st.image("logo.png", use_container_width=True)
        except: 
            pass
    st.markdown("<h2 style='text-align: center;'>💼 AFFILIATE LOGIN</h2>", unsafe_allow_html=True)
    with st.form("login", clear_on_submit=True):
        u = st.text_input("Username")
        p = st.text_input("Password", type="password")
        if st.form_submit_button("LOGIN", use_container_width=True):
            user = pd.read_sql_query("SELECT * FROM users WHERE username=? AND password=? AND role='AFFILIATE'", conn, params=(u, p))
            if not user.empty:
                status = user.iloc[0]['admin_status']
                if status == 'PENDING': 
                    st.warning("⏳ Account pending Admin approval.")
                elif status == 'REJECTED': 
                    st.error("❌ Account rejected. Contact Admin.")
                else:
                    st.session_state.logged_in, st.session_state.username, st.session_state.role = True, u, 'AFFILIATE'
                    st.rerun()
            else: 
                st.error("❌ Invalid credentials.")
    st.stop()

username = st.session_state.username
st.markdown("<h1 style='text-align: center;'>💼 AFFILIATE COMMAND CENTER</h1>", unsafe_allow_html=True)
top_col_logo, top_col1, top_col2 = st.columns([1, 4, 1])
with top_col_logo:
    try: 
        st.image("logo.png", use_container_width=True)
    except: 
        pass
with top_col2:
    if st.button("🔒 LOGOUT", use_container_width=True):
        st.session_state.clear()
        st.rerun()
st.divider()

try:
    promo_query = "SELECT title, message FROM admin_promos WHERE active = 1 AND (target = 'AFFILIATES' OR target = 'ALL USERS' OR target IS NULL) ORDER BY id DESC LIMIT 1"
    promo = pd.read_sql_query(promo_query, conn)
    if not promo.empty:
        st.markdown(f"""
        <div style="background-color: #004d40; color: white; padding: 15px; border-radius: 10px; text-align: center; margin-bottom: 20px;">
            <h2 style="margin:0;">📢 {promo.iloc[0]['title']}</h2>
            <p style="margin:0; font-size: 16px;">{promo.iloc[0]['message']}</p>
        </div>
        """, unsafe_allow_html=True)
except: 
    pass

tabs = st.tabs(["BOOKINGS & HANDOVER", "MY ASSETS", "ADD ASSET", "ADD DRIVER", "REVIEWS"])

with tabs[0]:
    st.markdown("<h3 style='text-align: center;'>🟡 PENDING DISPATCH (Handover flow)</h3>", unsafe_allow_html=True)
    pending = pd.read_sql_query("""
        SELECT b.id, b.renter_username, b.with_driver, b.pickup_time, b.booking_ref, u.full_name as renter_fullname, 
               v.make, v.model, v.plate FROM bookings b 
        JOIN vehicles v ON b.vehicle_id = v.id 
        JOIN users u ON b.renter_username = u.username 
        WHERE v.owner_username = ? AND b.status = 'CONFIRMED'
        ORDER BY b.pickup_time ASC""", conn, params=(username,))
    
    if pending.empty: 
        st.info("No vehicles pending handover.")
    for _, t in pending.iterrows():
        pickup_str = str(t['pickup_time'])[:16]
        b_ref = t.get('booking_ref') if pd.notnull(t.get('booking_ref')) else 'PENDING'
        with st.expander(f"🎫 #{b_ref} | 🗓️ {pickup_str} | RELEASE: {t['make']} {t['model']} ({t['plate']}) - Renter: {t['renter_fullname']}"):
            if f"contract_{t['id']}" in st.session_state:
                st.success("SUCCESS: Contract generated! Download to your phone & share via messenger.")
                st.download_button("📥 DOWNLOAD PDF CONTRACT", data=st.session_state[f"contract_{t['id']}"], file_name=f"Contract_{b_ref}.pdf", mime="application/pdf", use_container_width=True)
                if st.button("FINISH & RELEASE VEHICLE (START TRIP)", key=f"fin_{t['id']}", type="primary", use_container_width=True):
                    imgs = st.session_state.get(f"imgs_{t['id']}", [None]*10)
                    ass_driver = st.session_state.get(f"drv_{t['id']}", "")
                    conn.execute("""UPDATE bookings SET status = 'ONGOING', 
                                    front_img=?, back_img=?, left_img=?, right_img=?, odometer_img=?, 
                                    dseat_img=?, pseat_img=?, tire_img=?, trunk_img=?, actual_dl_img=?, 
                                    assigned_driver=? WHERE id = ?""", (*imgs, ass_driver, t['id']))
                    conn.commit()
                    for k in [f"contract_{t['id']}", f"imgs_{t['id']}", f"drv_{t['id']}"]:
                        if k in st.session_state: 
                            del st.session_state[k]
                    st.rerun()
            else:
                is_with_driver = t.get('with_driver', 0) == 1
                assigned_driver = ""
                can_proceed = True
                if is_with_driver:
                    st.warning("👨‍✈️ *DRIVER REQUIRED*")
                    my_drivers = pd.read_sql_query("SELECT first_name || ' ' || last_name as full_name FROM drivers WHERE owner_username = ? AND admin_status = 'APPROVED'", conn, params=(username,))
                    if my_drivers.empty: 
                        st.error("⚠️ No APPROVED drivers! Register one.")
                        can_proceed = False
                    else: 
                        assigned_driver = st.selectbox("Assign Driver:", my_drivers['full_name'].tolist(), key=f"d_sel_{t['id']}")
                if can_proceed:
                    chk_tank = st.checkbox("[ ] Full Tank", key=f"htank_{t['id']}")
                    chk_exterior = st.checkbox("[ ] Exterior car check OK", key=f"hext_{t['id']}")
                    chk_deposit = st.checkbox("[ ] Php 5k Deposit Confirmed", key=f"hdep_{t['id']}")
                    st.divider()
                    st.write("** BULK UPLOAD 10 PHOTOS (Required)**")
                    bulk_photos = st.file_uploader("Upload all photos", type=['jpg','png'], accept_multiple_files=True, key=f"bulk_{t['id']}")
                    st.divider()
                    c1, c2 = st.columns(2)
                    with c1:
                        st.write("Renter Signature")
                        sig_label_r = "Driver" if is_with_driver else "Affiliate"
                        if f"clr_sr_{t['id']}" not in st.session_state: 
                            st.session_state[f"clr_sr_{t['id']}"] = 0
                        s_r = st_canvas(stroke_width=2, stroke_color="#000", background_color="#eee", height=150, width=250, display_toolbar=False, key=f"sr_{t['id']}_{st.session_state[f'clr_sr_{t['id']}']}")
                        if st.button("Clear Renter", key=f"btn_sr_{t['id']}", use_container_width=True):
                            st.session_state[f"clr_sr_{t['id']}"] += 1
                            st.rerun()
                    with c2:
                        st.write(f"{sig_label_r} Signature")
                        if f"clr_sa_{t['id']}" not in st.session_state: 
                            st.session_state[f"clr_sa_{t['id']}"] = 0
                        s_a = st_canvas(stroke_width=2, stroke_color="#000", background_color="#eee", height=150, width=250, display_toolbar=False, key=f"sa_{t['id']}_{st.session_state[f'clr_sa_{t['id']}']}")
                        if st.button("Clear Partner", key=f"btn_sa_{t['id']}", use_container_width=True):
                            st.session_state[f"clr_sa_{t['id']}"] += 1
                            st.rerun()
                    if st.button("GENERATE CONTRACT & DISPATCH", key=f"ex_{t['id']}", type="primary", use_container_width=True):
                        has_sr = s_r.image_data is not None and len(s_r.json_data.get("objects", [])) > 0
                        has_sa = s_a.image_data is not None and len(s_a.json_data.get("objects", [])) > 0
                        if not (chk_tank and chk_exterior and chk_deposit): 
                            st.error("Check off all items.")
                        elif len(bulk_photos) < 10: 
                            st.error("Upload 10 required.")
                        elif not (has_sr and has_sa): 
                            st.error("Signatures required.")
                        else:
                            chk_items = ["Full Tank", "Exterior car check OK", "Php 5k Deposit Confirmed"]
                            b_ref_display = f"#{t['booking_ref']}" if pd.notnull(t.get('booking_ref')) else f"DRV-{t['id']:05d}"
                            try:
                                pdf_bytes = generate_contract(b_ref_display, t['renter_fullname'], f"{t['make']} {t['model']}", t['plate'], chk_items, s_r.image_data, s_a.image_data, is_with_driver, assigned_driver)
                                st.session_state[f"contract_{t['id']}"] = pdf_bytes
                                st.session_state[f"imgs_{t['id']}"] = [save_file(bulk_photos[i]) for i in range(10)]
                                st.session_state[f"drv_{t['id']}"] = assigned_driver
                                emails_df = pd.read_sql_query("SELECT email FROM users WHERE username IN (?, ?)", conn, params=(t['renter_username'], st.session_state.username))
                                renter_email = emails_df.iloc[0]['email'] if not emails_df.empty and len(emails_df) > 0 else None
                                affiliate_email = emails_df.iloc[1]['email'] if not emails_df.empty and len(emails_df) > 1 else None
                                subject = f"DriveElite: Handover Contract - {t['make']} {t['model']}"
                                body = "Attached is your legally binding handover agreement."
                                if renter_email: 
                                    send_pdf_email(renter_email, subject, body, pdf_bytes, f"Contract_{b_ref_display}.pdf")
                                if affiliate_email: 
                                    send_pdf_email(affiliate_email, subject, "Partner Copy: " + body, pdf_bytes, f"Contract_{b_ref_display}.pdf")
                                st.rerun()
                            except Exception as e: 
                                st.error(str(e))

    st.divider()
    st.markdown("<h3 style='text-align: center;'>🔵 ONGOING TRIPS (Returns flow)</h3>", unsafe_allow_html=True)
    ongoing = pd.read_sql_query("""
        SELECT b.id, b.vehicle_id, b.renter_username, b.with_driver, b.booking_ref, u.full_name as renter_fullname, 
               v.make, v.model, v.plate FROM bookings b 
        JOIN vehicles v ON b.vehicle_id = v.id 
        JOIN users u ON b.renter_username = u.username 
        WHERE v.owner_username = ? AND b.status = 'ONGOING'""", conn, params=(username,))
    
    if ongoing.empty: 
        st.info("No vehicles currently on the road.")
    for _, t in ongoing.iterrows():
        b_ref = t.get('booking_ref') if pd.notnull(t.get('booking_ref')) else 'PENDING'
        with st.expander(f"🎫 #{b_ref} | RECEIVE RETURN: {t['make']} {t['model']} ({t['plate']}) - Renter: {t['renter_fullname']}"):
            if f"ret_receipt_{t['id']}" in st.session_state:
                refund_amt = st.session_state[f"refund_{t['id']}"]
                st.success(f"SUCCESS: Settlement calculated! Refund: Php {refund_amt:,.2f}")
                st.download_button("📥 DOWNLOAD SETTLEMENT PDF", data=st.session_state[f"ret_receipt_{t['id']}"], file_name=f"Settlement_{b_ref}.pdf", mime="application/pdf", use_container_width=True)
                
                # --- FIXED DATABASE UPDATE BLOCK (REVENUE PROTECTED) ---
                if st.button("CLOSE BOOKING & RELEASE RENTER", key=f"fin_ret_{t['id']}", type="primary", use_container_width=True):
                    d_img_path = st.session_state.get(f"dmg_img_{t['id']}", None)
                    conn.execute("""
                        UPDATE bookings 
                        SET status = 'COMPLETED', 
                            damage_img = ? 
                        WHERE id = ?
                    """, (d_img_path, t['id']))
                    
                    conn.execute("UPDATE vehicles SET booking_status = 'AVAILABLE' WHERE id = ?", (t['vehicle_id'],))
                    conn.commit()
                    for k in [f"ret_receipt_{t['id']}", f"refund_{t['id']}", f"dmg_img_{t['id']}"]:
                        if k in st.session_state: 
                            del st.session_state[k]
                    st.rerun()
                # ---------------------------------------------------------
            else:
                is_with_driver = t.get('with_driver', 0) == 1
                c1, c2 = st.columns(2)
                with c1:
                    f_ok = st.checkbox("Fuel OK", value=True, key=f"f_{t['id']}")
                    fuel_deduct = 0.0
                    if not f_ok: 
                        fuel_refill = st.number_input("Fuel Refill Cost (Php)", step=100.0, key=f"f_cost_{t['id']}")
                        fuel_deduct = fuel_refill + 200.0
                    
                    c_ok = st.checkbox("Clean OK", value=True, key=f"c_{t['id']}")
                    clean_deduct = 0.0
                    if not c_ok: 
                        clean_deduct = st.number_input("Cleaning Penalty", min_value=0.0, max_value=500.0, step=100.0, value=500.0, key=f"c_cost_{t['id']}")
                    
                    r_ok = st.checkbox("RFID Balanced / Load OK", value=True, key=f"r_{t['id']}")
                    rfid_fee = 0.0
                    if not r_ok:
                        rfid_load = st.number_input("RFID Load Used", min_value=0.0, step=100.0, key=f"r_cost_{t['id']}")
                        rfid_fee = rfid_load + 200.0
                    
                    l_ok = st.checkbox("Returned on Time", value=True, key=f"l_{t['id']}")
                    late_deduct = 0.0
                    if not l_ok:
                        late_hrs = st.number_input("Hours Late", min_value=1, step=1, key=f"l_hrs_{t['id']}")
                        late_deduct = late_hrs * 300.0
                    
                    ot_fee = 0.0
                    if is_with_driver:
                        ot_ok = st.checkbox("Driver Hours OK", value=True, key=f"ot_chk_{t['id']}")
                        if not ot_ok:
                            ot_hrs = st.number_input("Overtime Hours", min_value=1, step=1, key=f"ot_hrs_{t['id']}")
                            ot_fee = ot_hrs * 200.0
                    
                    d_ok = st.checkbox("No Damage Found", value=True, key=f"d_{t['id']}")
                    damage_deduct = 0.0
                    img_damage = None
                    if not d_ok:
                        img_damage = st.file_uploader("Upload Damage Photos", type=['jpg','png'], accept_multiple_files=True, key=f"p_dam_{t['id']}")
                        dam_type = st.radio("Damage Type", ["Php 4k/panel", "Repair Est"], key=f"d_type_{t['id']}")
                        if dam_type == "Php 4k/panel":
                            panels = st.number_input("Damaged Panels", min_value=1, step=1, key=f"d_pan_{t['id']}")
                            damage_deduct = panels * 4000.0
                        else: 
                            damage_deduct = st.number_input("Estimate", step=500.0, key=f"d_est_{t['id']}")
                    
                    total_deduct = fuel_deduct + clean_deduct + damage_deduct + rfid_fee + late_deduct + ot_fee
                    refund_amount = 5000.0 - total_deduct
                    st.divider()
                    st.write(f"Total Deductions: Php {total_deduct:,.2f}")
                    if refund_amount < 0: 
                        st.error(f"OWES EXTRA: Php {abs(refund_amount):,.2f}")
                        refund_amount = 0.0
                    else: 
                        st.success(f"Deposit Refund: Php {refund_amount:,.2f}")
                with c2:
                    c_ret1, c_ret2 = st.columns(2)
                    with c_ret1:
                        st.write("Renter Final sign-off")
                        if f"clr_sret_{t['id']}" not in st.session_state: 
                            st.session_state[f"clr_sret_{t['id']}"] = 0
                        s_ret = st_canvas(stroke_width=2, stroke_color="#000", background_color="#eee", height=150, width=150, display_toolbar=False, key=f"sret_{t['id']}_{st.session_state[f'clr_sret_{t['id']}']}")
                        if st.button("Clear Renter", key=f"btn_sret_{t['id']}", use_container_width=True): 
                            st.session_state[f"clr_sret_{t['id']}"] += 1
                            st.rerun()
                    with c_ret2:
                        st.write("Partner Final sign-off")
                        if f"clr_sreta_{t['id']}" not in st.session_state: 
                            st.session_state[f"clr_sreta_{t['id']}"] = 0
                        s_reta = st_canvas(stroke_width=2, stroke_color="#000", background_color="#eee", height=150, width=150, display_toolbar=False, key=f"sreta_{t['id']}_{st.session_state[f'clr_sreta_{t['id']}']}")
                        if st.button("Clear Partner", key=f"btn_sreta_{t['id']}", use_container_width=True): 
                            st.session_state[f"clr_sreta_{t['id']}"] += 1
                            st.rerun()
                if st.button("GENERATE SETTLEMENT & COMPLETE JOURNEY", key=f"comp_{t['id']}", type="primary", use_container_width=True):
                    has_sret = s_ret.image_data is not None and len(s_ret.json_data.get("objects", [])) > 0
                    has_sreta = s_reta.image_data is not None and len(s_reta.json_data.get("objects", [])) > 0
                    if not d_ok and not img_damage: 
                        st.error("Damage photo required.")
                    elif has_sret and has_sreta:
                        b_ref_display = f"#{t['booking_ref']}" if pd.notnull(t.get('booking_ref')) else f"DRV-{t['id']:05d}"
                        try:
                            pdf_bytes = generate_return_receipt(b_ref_display, t['renter_fullname'], f"{t['make']} {t['model']}", t['plate'], fuel_deduct, clean_deduct, damage_deduct, late_deduct, ot_fee, rfid_fee, total_deduct, refund_amount, s_ret.image_data, s_reta.image_data)
                            st.session_state[f"ret_receipt_{t['id']}"] = pdf_bytes
                            st.session_state[f"refund_{t['id']}"] = refund_amount
                            if img_damage:
                                saved_paths = [save_file(img) for img in img_damage]
                                st.session_state[f"dmg_img_{t['id']}"] = ",".join(filter(None, saved_paths))
                            else: 
                                st.session_state[f"dmg_img_{t['id']}"] = None
                            emails_df = pd.read_sql_query("SELECT email FROM users WHERE username IN (?, ?)", conn, params=(t['renter_username'], st.session_state.username))
                            renter_email = emails_df.iloc[0]['email'] if not emails_df.empty else None
                            affiliate_email = emails_df.iloc[1]['email'] if not emails_df.empty and len(emails_df) > 1 else None
                            subject = f"DriveElite: Return Receipt - {t['make']} {t['model']}"
                            body = "Attached is your settlement receipt."
                            if renter_email: 
                                send_pdf_email(renter_email, subject, body, pdf_bytes, f"Settlement_{b_ref_display}.pdf")
                            if affiliate_email: 
                                send_pdf_email(affiliate_email, subject, "Partner Copy: " + body, pdf_bytes, f"Settlement_{b_ref_display}.pdf")
                            st.rerun()
                        except Exception as e: 
                            st.error(str(e))
                    else: 
                        st.error("NOTICE: Both must sign.")

with tabs[1]:
    st.markdown("<h3 style='text-align: center;'>MY FLEET CONTROLS</h3>", unsafe_allow_html=True)
    fleet = pd.read_sql_query("SELECT id, make, model, plate, booking_status, admin_status, ref_no FROM vehicles WHERE owner_username = ?", conn, params=(username,))
    if fleet.empty: 
        st.info("You haven't added any vehicles yet.")
    for _, c in fleet.iterrows():
        v_ref = c.get('ref_no') if pd.notnull(c.get('ref_no')) else 'PENDING'
        with st.expander(f"🚗 #{v_ref} | {c['make']} {c['model']} - Status: {c['booking_status']} (Admin: {c['admin_status']})"):
            if c['admin_status'] == 'APPROVED':
                if c['booking_status'] == 'AVAILABLE' and st.button("Hide Vehicle", key=f"h_{c['id']}"):
                    conn.execute("UPDATE vehicles SET booking_status = 'UNAVAILABLE' WHERE id = ?", (c['id'],))
                    conn.commit()
                    st.rerun()
                elif c['booking_status'] == 'UNAVAILABLE' and st.button("Repost Vehicle", key=f"s_{c['id']}"):
                    conn.execute("UPDATE vehicles SET booking_status = 'AVAILABLE' WHERE id = ?", (c['id'],))
                    conn.commit()
                    st.rerun()

with tabs[2]:
    st.markdown("<h3 style='text-align: center;'>REGISTER A VEHICLE</h3>", unsafe_allow_html=True)
    with st.form("add_v"):
        cat = st.selectbox("CATEGORY", list(FIXED_RATES.keys()))
        c1, c2 = st.columns(2)
        ma = c1.text_input("MAKE (Nissan)")
        mo = c2.text_input("MODEL (Terra VE)")
        ye = c1.text_input("YEAR")
        pl = c2.text_input("PLATE")
        c3, c4 = st.columns(2)
        bn = c3.text_input("PAYOUT BANK (BDO, BPI, GCash)")
        an = c4.text_input("ACCOUNT NUMBER")
        c5, c6, c7 = st.columns(3)
        vi = c5.file_uploader("Vehicle Photo", type=['jpg','png'])
        orc = c6.file_uploader("OR/CR Doc", type=['jpg','png'])
        ins = c7.file_uploader("Comprehensive Insurance", type=['jpg','png'])
        if st.form_submit_button("SUBMIT FOR APPROVAL", type="primary"):
            if ma and mo and pl and bn and an and vi and orc and ins:
                new_ref_no = str(random.randint(100000, 999999))
                conn.execute("""
                    INSERT INTO vehicles (owner_username, make, model, year, plate, bank_name, account_no, vehicle_img, or_cr_img, insurance_img, category, approved_price, ref_no) 
                    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
                """, (username, ma.title(), mo.title(), ye, pl.upper(), bn, an, save_file(vi), save_file(orc), save_file(ins), cat, FIXED_RATES.get(cat,0), new_ref_no))
                conn.commit()
                st.success(f"SUCCESS: Vehicle Submitted! Ref #{new_ref_no}.")
            else: 
                st.error("Please fill all required fields.")

with tabs[3]:
    st.markdown("<h3 style='text-align: center;'>REGISTER A DRIVER</h3>", unsafe_allow_html=True)
    with st.form("add_d"):
        c1, c2, c3 = st.columns(3)
        df_first = c1.text_input("First Name").title()
        df_mid = c2.text_input("Middle Name").title()
        df_last = c3.text_input("Last Name").title()
        c_contact, c_age = st.columns(2)
        d_contact = c_contact.text_input("Contact No.")
        d_age = c_age.number_input("Age", min_value=18, max_value=99, step=1)
        d_address = st.text_area("Full Address")
        is_owner = st.checkbox("I am the driver (Owner driving)")
        st.write("*Identity Verification (2 IDs Required)*")
        c6, c7 = st.columns(2)
        d_gov = c6.file_uploader("Upload Govt ID", type=['jpg','png'])
        d_lic = c7.file_uploader("Upload Professional License", type=['jpg','png'])
        if st.form_submit_button("SUBMIT DRIVER FOR APPROVAL", type="primary"):
            if df_first and df_last and d_contact and d_gov and d_lic:
                conn.execute("INSERT INTO drivers (owner_username, first_name, middle_name, last_name, age, address, contact_number, is_owner, govt_id_img, license_img, admin_status) VALUES (?,?,?,?,?,?,?,?,?,?, 'PENDING')", (username, df_first, df_mid, df_last, d_age, d_address, d_contact, 1 if is_owner else 0, save_file(d_lic), save_file(d_gov)))
                conn.commit()
                st.success("SUCCESS: Driver Submitted!")
            else: 
                st.error("Please fill required fields.")
    try:
        my_drivers = pd.read_sql_query("SELECT first_name, last_name, contact_number, admin_status FROM drivers WHERE owner_username = ?", conn, params=(username,))
        if not my_drivers.empty: 
            st.markdown("### MY DRIVERS")
            st.dataframe(my_drivers, hide_index=True, use_container_width=True)
        else: 
            st.info("No drivers registered.")
    except: 
        pass

with tabs[4]:
    st.markdown("<h3 style='text-align: center;'>⭐ Guest Reviews for Your Fleet</h3>", unsafe_allow_html=True)
    query_reviews = """
        SELECT b.rating, b.review, b.pickup_time, u.full_name as renter_name,
               v.make, v.model, v.plate
        FROM bookings b
        JOIN vehicles v ON b.vehicle_id = v.id
        JOIN users u ON b.renter_username = u.username
        WHERE v.owner_username = ? AND b.rating IS NOT NULL
        ORDER BY b.id DESC
    """
    try:
        reviews_df = pd.read_sql_query(query_reviews, conn, params=(st.session_state.username,))
        if reviews_df.empty: 
            st.info("No reviews yet!")
        else:
            for _, rev in reviews_df.iterrows():
                stars = "⭐" * int(rev['rating'])
                trip_date = str(rev['pickup_time'])[:10]
                with st.container(border=True):
                    st.markdown(f"#### {stars} - {rev['make']} {rev['model']} ({rev['plate']})")
                    st.caption(f"🕵️‍♂️ Renter: {rev['renter_name']} | 📅 Date: {trip_date}")
                    if pd.notna(rev['review']) and str(rev['review']).strip():
                        st.info(f"💬 \"{rev['review']}\"")
    except Exception as e: 
        st.error("Review database syncing...")

# ==========================================
# AFFILIATE SIDEBAR (My Documents)
# ==========================================
with st.sidebar:
    st.write(f"### 👤 Affiliate Profile")
    st.write(f"**Fleet Owner:** {st.session_state.username}")
    
    # Fetch their specific MOA link from the database
    user_doc = pd.read_sql_query(
        "SELECT document_url FROM users WHERE username=?", 
        conn, 
        params=(st.session_state.username,)
    )
    
    if not user_doc.empty and pd.notnull(user_doc.iloc[0]['document_url']):
        doc_link = user_doc.iloc[0]['document_url']
        st.success("Fleet Partner Verified ✅")
        st.link_button("📄 View Signed MOA", doc_link, use_container_width=True)
    else:
        st.warning("⚠️ No signed MOA found.")
    
    st.divider()
    st.caption("Need help? Contact DriveElite Admin.")
# ==========================================
